### ISSUE TITLE
03-date: isLeapYear

### ISSUE THREAD

**Issue by Kalita-Roman** [gagarin880120/js-assignments#1]
https://github.com/gagarin880120/js-assignments/blob/5bb590036ef4ab67c1844deb754a16ecd81fb3a7/task/03-date-tasks.js#L57-L61
Просто ремарка по codestyle. Обычно не делают вложенные тернанрые операторы. Считается что это сложнее для восприятия того что происходит в коде. 
Тут в тестах есть ограничение по кол-ву строк кода в функции. Поэтому, возможно, не получится расписать это подробнее.

**Comment by andrejmandryk** [comment]
я поэтому так и делал (из-за ограничения на количество строк)
