### ISSUE TITLE
04-arrays: sortCitiesArray

### ISSUE THREAD

**Issue by Kalita-Roman** [gagarin880120/js-assignments#6]
https://github.com/gagarin880120/js-assignments/blob/641aecb9691bfab51405ca7d0b6fecf1f0927105/task/04-arrays-tasks.js#L422-L431
Тут есть такое хитрое решение
```
function sortCitiesArray(arr) {
  return arr.sort((a, b) => a.country.localeCompare(b.country) || a.city.localeCompare(b.city));
}
```

**Comment by andrejmandryk** [comment]
круто!) ни разу не пользовался этим методом
